### ISSUE TITLE
Installation on Mac and Python Django Virtual Env

### ISSUE THREAD

**Issue by 2sama** [nihal223/Stock-Forecaster#1]
Hi,

Could you please provide a more detailed guideline on installing Stock-Forecaster system on an active Django virtual environment? 
           (DjangoVirtualEnv) sam:~ akwa$
Thanks

**Comment by nihal223** [comment]
Hey,
You can just follow the steps in the README to run this project on the Django server. Is there anything specific thing you are stuck at?
